
//
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
//
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
//
// It was generated at 2022-10-25T16:23:23.752883 by raph on ENNS-WORK
//
// a8-versions build/versioning info follows
//
//        build_date : Tue Oct 25 06:45:32 EDT 2022
//        build_machine : stella.local
//        build_user : glen
//


val appVersion = a8.sbt_a8.versionStamp(file("."))

val scalaLibVersion = "3.2.2"
val httpServerVersion = "1.0.0-20230518_1328_master"

Global / scalacOptions ++= Seq("-deprecation", "-unchecked", "-feature")

Global / resolvers += ("a8-repo" at Common.readRepoUrl()).withAllowInsecureProtocol(true)
Global / publishTo := Some(("a8-repo-releases" at Common.readRepoUrl()).withAllowInsecureProtocol(true))
Global / credentials += Common.readRepoCredentials()

//Global / publishTo := sonatypePublishToBundle.value
//Global / credentials += Credentials(Path.userHome / ".sbt" / "sonatype.credentials")

Global / scalaVersion := scalaLibVersion

Global / organization := "io.accur8"

Global / version := appVersion

Global / versionScheme := Some("strict")

Global / serverConnectionType := ConnectionType.Local


lazy val locus =
  Common
    .jvmProject("a8-request-sink", file("."), "request-sink")
    .settings(
      libraryDependencies ++= Seq(

        compilerPlugin("com.github.ghik" % "zerowaste" % "0.2.6" cross CrossVersion.full),

        "dev.zio" %% "zio-http" % "3.0.0-RC1",
        "io.accur8" %% "a8-http-server" % httpServerVersion % "compile" exclude("org.scala-lang.modules", "scala-collection-compat_2.13"),

        "org.scalatest" %% "scalatest" % "3.2.14" % Test,

      )
    )


   
